name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: install_dependencies_macos
        if: runner.os == 'MacOS'
        run: |
          brew install llvm
          brew install libomp
          # Add Homebrew paths to path.
          echo "PATH=$(brew --prefix)/bin:$(brew --prefix)/opt/llvm/bin:$(brew --prefix)/opt/libomp/bin:$PATH" >> $GITHUB_ENV
          echo "CC=$(brew --prefix)/opt/llvm/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix)/opt/llvm/bin/clang++" >> $GITHUB_ENV


      - name: build_wheels
        uses: pypa/cibuildwheel@v2.16.5

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
